platform :ios, '10.0'
use_frameworks!

inhibit_all_warnings!

target 'DKImagePickerControllerDemo' do

  pod 'DKPhotoGallery', :git => 'https://github.com/vvlee/DKPhotoGallery.git', :tag => '1.0.2'
  pod 'DKImagePickerController', :path => '../'

  # Pods for DKImagePickerControllerDemo

  target 'DKImagePickerControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
